const Strings = {
  name: 'Please Enter Your Name',
  username: 'Please Enter Username ',
  password: 'Please Enter Password',
  confirmPassword: 'Please Confirm Password',
  phoneNo: 'Please Enter Phone Number',
  email: 'Please Enter Your Email ',
  emailorphone: 'Enter Email or Phone Number',
  getotp: 'Get OTP',
  greet: 'Welcome Back!',
  resetpassword: 'Reset password?',
  forgetpassword: 'Forgot Password?',
  donthaveaccount: "Don't have account?",
  signup: 'Sign Up',
  alreadyuser: 'Already User?',
  login: 'Login',
  addtocart: 'Add To Cart',
  buynow: 'Buy Now',
  offers: 'Get more offers',
  search: 'Search Here',
  review: ' Reviews',
  categories: 'Categories',
  loader: 'Loading Please Wait...',
  stock: 'Instock',
  currency: '$',
  plusSign: '+',
  minusSign: '-',
  noproduct: 'No products available',
};
export default Strings;
